spring.application.name=BancoDeDados

spring.datasource.url=jdbc:postgresql://db.mdxdtohklaqwbhazssvi.supabase.co:5432/postgres;
spring.datasource.username=postgres
spring.datasource.password=rpzYWadTSFERbxO3

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true