spring.application.name=BancoDeDados

spring.datasource.url=jdbc:postgresql:mdxdtohklaqwbhazssvi.supabase.co
spring.datasource.username=postgres
spring.datasource.password=sb_publishable_H4lRm8_FP_s9n8rEo4XzCw_picNSGdL

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true